kind: Deployment 
apiVersion: apps/v1
metadata:
  name: mongodb-deployment
  namespace: chat-app
  labels:
    app: database 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database 
    spec:
      containers:
        - name: mongodb-ctr
          image: mongo:latest
          ports:
           - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root